server:
  port: 8080
spring:
  application:
    name: gateway
  profiles:
    active: dev
zuul:
  routes:
    api-test:
      path: /api/clientTest/**
      serviceId: test
    api-blog:
      path: /api/blog/**
      serviceId: blog
    api-tools:
      path: /api/tools/**
      serviceId: tools
    api-user:
      path: /api/user/**
      serviceId: user
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 100000
  ribbon:
    eager-load:
      enabled: true
      clients: blog, tools, user
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000
ribbon:  
  ReadTimeout: 100000
  ConnectTimeout: 100000
