server:
  port: 8083
spring:
  application:
    name: gateway
  profiles:
    active: dev
zuul:
  routes:
    api-blog:
      path: /blog/**
      serviceId: blog
    api-tools:
      path: /tools/**
      serviceId: tools
    api-user:
      path: /user/**
      serviceId: user
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 100000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000
ribbon:  
  ReadTimeout: 100000
  ConnectTimeout: 100000
  MaxAutoRetries: 0 
  MaxAutoRetriesNextServer: 1 
  eureka: 
    enabled: true
