server:
  port: 8080
spring:
  application:
    name: gateway
  profiles:
    active: dev
zuul:
  routes:
    api-test:
      path: /api/clientTest/**
      serviceId: test
    api-blog:
      path: /api/blog/**
      serviceId: blog
    api-tools:
      path: /api/tools/**
      serviceId: tools
    api-user:
      path: /api/user/**
      serviceId: user
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  semaphore:
        max-semaphores: 200
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:  
  ReadTimeout: 60000
  ConnectTimeout: 60000
